# Generated by Django 6.0.4 on 2026-05-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('category', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
    ]
