# Generated by Django 6.0.4 on 2026-05-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
