# Generated by Django 6.0.4 on 2026-05-17 09:10

from django.db import migrations


def delete_all_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.all().delete()


def reverse_delete_users(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_profile_budget_alter_profile_goal'),
    ]

    operations = [
        migrations.RunPython(delete_all_users, reverse_delete_users),
    ]
