# Generated by Django 6.0.4 on 2026-05-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_all_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_wishlist',
            field=models.BooleanField(default=False, help_text='True if this expense is a purchased wishlist item'),
        ),
    ]
