# Generated by Django 6.0.4 on 2026-05-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price is required for wishlist items', max_digits=10),
            preserve_default=False,
        ),
    ]
